### ISSUE TITLE
error for incoming messages

### ISSUE THREAD

**Issue by transfluxus** [windkh/node-red-contrib-telegrambot#10]
Hi that's I get when I want to send the incoming telegram messages into the console..

```
[error] [chatbot-telegram-node:ef3e82ff.79d3b] Unable to find context().global in Node-RED 
Unhandled rejection TypeError: Cannot read property 'set' of undefined
    at TelegramBotNode.handleMessage (/Users/x/.node-red/node_modules/node-red-contrib-chatbot/chatbot-telegram-receive.js:193:18)
    at TelegramBot.emit (/Users/x/.node-red/node_modules/eventemitter3/index.js:116:35)
...
```

**Comment by windkh** [comment]
Hi, you reported this issue to the wrong project. Please go to node-red-contrib-chatbot.
