### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by RogierQ** [windkh/node-red-contrib-telegrambot#135]
i am getting this in my log but not in the error node in node red

Unhandled rejection Error: ETELEGRAM: 403 Forbidden: bot was blocked by the user
    at /home/qusax/.node-red/node_modules/node-telegram-bot-api/src/telegram.js:284:15
    at tryCatcher (/home/qusax/.node-red/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/qusax/.node-red/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/qusax/.node-red/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/qusax/.node-red/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/qusax/.node-red/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/qusax/.node-red/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/qusax/.node-red/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/qusax/.node-red/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/qusax/.node-red/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by windkh** [comment]
Hm I am not sure if this kond of error can be intercepted... I will finf out.
For a list of Telegram errors see https://core.telegram.org/api/errors

**Comment by RogierQ** [comment]
Ok, would be great if you can. Now it is very hard to detect why the loop stops running

**Comment by windkh** [comment]
fixed in 8.7.2
sorry for inconvenience. Message id was removed by accident. Should work again.

**Comment by RogierQ** [comment]
Is it correct that the update isnt available on the Node red palette?

**Comment by windkh** [comment]
it takes some time
