### ISSUE TITLE
TypeError: node.telegramBot[type] is not a function

### ISSUE THREAD

**Issue by gpongelli** [windkh/node-red-contrib-telegrambot#144]
Hi,
first of all, thanks for this awesome package!

I've just updated to v8.8.0, now my nodered flow throws an exception when sending "is typing" message to chat.

Some info:
- nodered v1.2.1
- this package v8.8.0

Message sent to sender node, coming from your examples
```
var msg = {"payload": {
                "chatId" : <chatId>, 
                "type" : 'action', 
                "content" : "typing"
                }
            };
```

Error message
```
{"message":"TypeError: node.telegramBot[type] is not a function",
"source":{
    "id":"......",
    "type":"telegram sender",
    "name":"send typing",
    "count":1},
"stack":"TypeError: node.telegramBot[type] is not a function\n
    at TelegramOutNode.processMessage (/data/node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js:1576:55)\n
    at TelegramOutNode._inputCallback (/data/node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js:1695:30)\n
    at hooks.trigger (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26)\n
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/runtime/lib/hooks.js:113:9)\n
    at TelegramOutNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)\n
    at TelegramOutNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)\n
    at TelegramOutNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)\n
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:652:52)\n    at runCallback (timers.js:705:18)\n
    at tryOnImmediate (time..."}
```

Thank you!

**Comment by windkh** [comment]
I will check this...

**Comment by windkh** [comment]
what example did you take?

**Comment by windkh** [comment]
Thanks for reporting. I reproduced the bug. Sorry for inconvenience ... this was introduced during refactoring.
Version 8.8.2 fixed this.
you can use "action" or "sendChatAction" beginning from that version.
