### ISSUE TITLE
 Unhandled rejection Error: ETELEGRAM: 409 Conflict

### ISSUE THREAD

**Issue by S474N** [windkh/node-red-contrib-telegrambot#307]
Noreded 3.0.2
node-red-contrib-telegrambot 15.1.1
docker-compose 2.17.3

Nodered in Docker, restarting about every hour, using only Telegram sender, full log of this:

```
08. 05. 2023 15:18:24
Unhandled rejection Error: ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
08. 05. 2023 15:18:24
    at /data/node_modules/node-telegram-bot-api/src/telegram.js:299:15
08. 05. 2023 15:18:24
    at tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
08. 05. 2023 15:18:24
    at Promise._settlePromiseFromHandler (/data/node_modules/bluebird/js/release/promise.js:547:31)
08. 05. 2023 15:18:24
    at Promise._settlePromise (/data/node_modules/bluebird/js/release/promise.js:604:18)
08. 05. 2023 15:18:24
    at Promise._settlePromise0 (/data/node_modules/bluebird/js/release/promise.js:649:10)
08. 05. 2023 15:18:24
    at Promise._settlePromises (/data/node_modules/bluebird/js/release/promise.js:729:18)
08. 05. 2023 15:18:24
    at _drainQueueStep (/data/node_modules/bluebird/js/release/async.js:93:12)
08. 05. 2023 15:18:24
    at _drainQueue (/data/node_modules/bluebird/js/release/async.js:86:9)
08. 05. 2023 15:18:24
    at Async._drainQueues (/data/node_modules/bluebird/js/release/async.js:102:5)
08. 05. 2023 15:18:24
    at Immediate.Async.drainQueues [as _onImmediate] (/data/node_modules/bluebird/js/release/async.js:15:14)
08. 05. 2023 15:18:24
    at processImmediate (internal/timers.js:464:21)
08. 05. 2023 15:19:28
Unhandled rejection Error: ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
08. 05. 2023 15:19:28
    at /data/node_modules/node-telegram-bot-api/src/telegram.js:299:15
08. 05. 2023 15:19:28
    at tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
08. 05. 2023 15:19:28
    at Promise._settlePromiseFromHandler (/data/node_modules/bluebird/js/release/promise.js:547:31)
08. 05. 2023 15:19:28
    at Promise._settlePromise (/data/node_modules/bluebird/js/release/promise.js:604:18)
08. 05. 2023 15:19:28
    at Promise._settlePromise0 (/data/node_modules/bluebird/js/release/promise.js:649:10)
08. 05. 2023 15:19:28
    at Promise._settlePromises (/data/node_modules/bluebird/js/release/promise.js:729:18)
08. 05. 2023 15:19:28
    at _drainQueueStep (/data/node_modules/bluebird/js/release/async.js:93:12)
08. 05. 2023 15:19:28
    at _drainQueue (/data/node_modules/bluebird/js/release/async.js:86:9)
08. 05. 2023 15:19:28
    at Async._drainQueues (/data/node_modules/bluebird/js/release/async.js:102:5)
08. 05. 2023 15:19:28
    at Immediate.Async.drainQueues [as _onImmediate] (/data/node_modules/bluebird/js/release/async.js:15:14)
08. 05. 2023 15:19:28
    at processImmediate (internal/timers.js:464:21)
```

**Comment by windkh** [comment]
This happens when 
- you have two config nodes using the same token
- or you use the same token on different machines at the same time

See error : "make sure that only one bot instance is running"

**Comment by S474N** [comment]
I turned off polling. Is it necessary, if I want only send status messages from NR?

**Comment by windkh** [comment]
If you want to only send messages you can turn polling off, yes

**Comment by S474N** [comment]
Ok, turned off polling and also discovered, that same configuration was used in another docker container.

**Comment by jerome6994** [comment]
Hello, I have the same problem with this error but I don't have any other instances in node red or another node red docker.

On the other hand I have telegram in Home Assistant and in node red does this correspond to the case of this error?

Because I need it in both applications at the moment

Thank you very much for your response
