### ISSUE TITLE
Unhandled rejection RequestError

### ISSUE THREAD

**Issue by bladerunner2020** [windkh/node-red-contrib-telegrambot#33]
If DNS is not configured properly telegram bot displays not errors, but there are errors in the node red log:

Unhandled rejection RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
    at new RequestError (/home/piv/.node-red/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/piv/.node-red/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/piv/.node-red/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/piv/.node-red/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/piv/.node-red/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by windkh** [comment]
How can I reproduce this? What do you mean with DNS not configured properly?

**Comment by windkh** [comment]
Version 2.9.0 supports configuration of a baseapiurl and enhanced error handling
