### ISSUE TITLE
Can't update package

### ISSUE THREAD

**Issue by thalesmaoa** [windkh/node-red-contrib-telegrambot#371]
Hi there, I've been using the package for a long time. It suddenly stop working. 
I first though that may be some telegram update and I should upgrade my package, but I can't:

```
$ cat /data/.npm/_logs/2024-04-26T19_03_41_880Z-debug-0.log
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.2
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 30ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 11ms
6 timing config:load:builtin Completed in 16ms
7 warn config production Use `--omit=dev` instead.
8 timing config:load:cli Completed in 40ms
9 timing config:load:env Completed in 4ms
10 timing config:load:file:/data/.npmrc Completed in 1ms
11 timing config:load:project Completed in 15ms
12 timing config:load:file:/usr/src/node-red/.npmrc Completed in 11ms
13 timing config:load:user Completed in 13ms
14 timing config:load:file:/usr/local/etc/npmrc Completed in 31ms
15 timing config:load:global Completed in 32ms
16 timing config:load:validate Completed in 4ms
17 timing config:load:credentials Completed in 14ms
18 timing config:load:setEnvs Completed in 15ms
19 timing config:load Completed in 198ms
20 timing npm:load:configload Completed in 202ms
21 timing npm:load:mkdirpcache Completed in 19ms
22 timing npm:load:mkdirplogs Completed in 5ms
23 verbose title npm install node-red-contrib-telegrambot@15.1.9
24 verbose argv "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix" "~" "--production" "--engine-strict" "node-red-contrib-telegrambot@15.1.9"
25 timing npm:load:setTitle Completed in 29ms
26 timing config:load:flatten Completed in 50ms
27 timing npm:load:display Completed in 85ms
28 verbose logfile logs-max:10 dir:/data/.npm/_logs
29 verbose logfile /data/.npm/_logs/2024-04-26T19_03_41_880Z-debug-0.log
30 timing npm:load:logFile Completed in 83ms
31 timing npm:load:timers Completed in 1ms
32 timing npm:load:configScope Completed in 1ms
33 timing npm:load Completed in 440ms
34 timing arborist:ctor Completed in 11ms
35 silly logfile start cleaning logs, removing 1 files
36 silly logfile done cleaning log files
37 timing idealTree:init Completed in 2765ms
38 timing idealTree:userRequests Completed in 46ms
39 silly idealTree buildDeps
40 silly fetch manifest node-red-contrib-telegrambot@15.1.9
41 timing arborist:ctor Completed in 2ms
42 http fetch GET 200 https://registry.npmjs.org/node-red-contrib-telegrambot 87461ms (cache stale)
43 silly placeDep ROOT node-red-contrib-telegrambot@ REPLACE for: node-red-project@0.0.1 want: 15.1.9
44 timing idealTree:#root Completed in 87711ms
45 timing idealTree:node_modules/node-red-contrib-telegrambot Completed in 0ms
46 timing idealTree:buildDeps Completed in 87723ms
47 timing idealTree:fixDepFlags Completed in 15ms
48 timing idealTree Completed in 90564ms
49 timing command:install Completed in 90660ms
50 verbose type version
51 verbose stack node-red-contrib-telegrambot: No matching version found for node-red-contrib-telegrambot@15.1.9.
51 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
51 verbose stack     at RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
51 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:19)
51 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
51 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
51 verbose stack     at async Promise.all (index 1)
51 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
51 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:145:5)
51 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
52 verbose cwd /data
53 verbose Linux 6.6.20+rpt-rpi-v8
54 verbose node v16.20.2
55 verbose npm  v8.19.4
56 error code ETARGET
57 error notarget No matching version found for node-red-contrib-telegrambot@15.1.9.
58 error notarget In most cases you or one of your dependencies are requesting
58 error notarget a package version that doesn't exist.
59 verbose exit 1
60 timing npm Completed in 92816ms
61 verbose unfinished npm timer reify 1714158224011
62 verbose unfinished npm timer reify:loadTrees 1714158224070
63 verbose code 1
64 error A complete log of this run can be found in:
64 error     /data/.npm/_logs/2024-04-26T19_03_41_880Z-debug-0.log
```

I have no clue about it.

**Comment by windkh** [comment]
Hm no idea. But I will just rerelease itband then lets try again

**Comment by windkh** [comment]
15.1.10

**Comment by thalesmaoa** [comment]
Ok, I found the problem. It was a dns problem inside my docker container. 
Now I did update it, however, it is complaining.

```
"No session: login first."
```

The layout is different from before and from docs.

![image](https://github.com/windkh/node-red-contrib-telegrambot/assets/14074573/ca03b004-17fa-498a-b39c-76e3b2315143)

Do I have to create an API now? Token isn't enough?

**Comment by windkh** [comment]
There are two types ogf telegram bot nodes
Node-red-contrib-telegrambot and node-red-node-telegrambot

The later one uses mtproto api the first one bot api.
I guess you just installed the mtproto one

**Comment by thalesmaoa** [comment]
Yes. My mistake. I noticed after posting.
Thx for the help.
