### ISSUE TITLE
Unhandled rejection Error: ETELEGRAM: 429 Too Many Requests *and* Unhandled rejection Error: ETELEGRAM: 502 Bad Gateway

### ISSUE THREAD

**Issue by Bobo-amg** [windkh/node-red-contrib-telegrambot#373]
Ok, perhaps I do have some sort of issue, but again it seems to point to a comms interruption somewhere.

Here are the full errors this time ...

Unhandled rejection Error: ETELEGRAM: 429 Too Many Requests: retry after 5
    at /home/main/.node-red/node_modules/node-telegram-bot-api/src/telegram.js:299:15
    at tryCatcher (/home/main/.node-red/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/main/.node-red/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/main/.node-red/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/main/.node-red/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/main/.node-red/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
Unhandled rejection Error: ETELEGRAM: 502 Bad Gateway
    at /home/main/.node-red/node_modules/node-telegram-bot-api/src/telegram.js:299:15
    at tryCatcher (/home/main/.node-red/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/main/.node-red/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/main/.node-red/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/main/.node-red/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/main/.node-red/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/main/.node-red/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)

**Comment by windkh** [comment]
Hm can you provide a screenshot of your configuration?

**Comment by Bobo-amg** [comment]
5 May 18:01:09 - [info] Node-RED version: v3.1.9
5 May 18:01:09 - [info] Node.js  version: v18.20.2
5 May 18:01:09 - [info] Linux 6.1.21-v8+ arm64 LE

Was running Node.js v16. I upgraded to Node.js v20 and errors spiralled out of control. Something about unhandled exception Aggregator. This may well have been the Aggregator node causing some of the errors. Have deleted it.

I also got
[node-red-contrib-telegrambot/telegrambot] Error: Cannot find module 'pump'
Require stack:
- /home/main/.node-red/node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js

**I downgraded to Node.js v18 and re-installed node-red-contrib-telegrambot.**

Everything is stable atm. Just waiting for 24hrs to see what happens.

**Comment by windkh** [comment]
Yes upgrading or testing the latest nodejs version is still on my list

**Comment by Bobo-amg** [comment]
Initial problem occurred using nodejs v16. Perhaps that in combination with Node-red v3.x was also causing some problems? Or unlikely?

**Comment by Bobo-amg** [comment]
One error in the last 16 hrs. Certainly looks like a comms issue somewhere. 

Can these errors be logged by NR?

5 May 19:53:46 - [warn] [telegram bot:5bab5b9af4f47a05] EFATAL: Error: read ECONNRESET
5 May 19:53:46 - [warn] [telegram bot:5bab5b9af4f47a05] _Network connection may be down. Trying again._
Unhandled rejection RequestError: Error: read ECONNRESET
    at new RequestError (/home/main/.node-red/node_modules/request-promise-core/lib/errors.js:14:15)
    at plumbing.callback (/home/main/.node-red/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/main/.node-red/node_modules/request-promise-core/lib/plumbing                                                  .js:46:31)
    at self.callback (/home/main/.node-red/node_modules/request/request.js:185:22)
    at Request.emit (node:events:517:28)
    at Request.onRequestError (/home/main/.node-red/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by windkh** [comment]
please try with new version 16.0.0
