### ISSUE TITLE
Telegram bot crashes nodered on startup, if internet is lost

### ISSUE THREAD

**Issue by slev1n** [windkh/node-red-contrib-telegrambot#377]
hi,

I had an internet outage yesterday. Unfortunately nodered crashed also because of telegram bot:
`<div class="MuiGrid-root MuiGrid-container MuiGrid-item css-n6nfem" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; display: flex; flex-flow: wrap; width: 2389.852783px; margin: 0px; -webkit-box-align: center; align-items: center; max-width: none; caret-color: rgb(255, 255, 255); color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12.000001px;"><span aria-label="Fehler anzeigen" class="MuiBadge-root css-1rzb3uu" style="box-sizing: inherit; position: relative; display: inline-flex; vertical-align: middle; flex-shrink: 0;"><span class="MuiBadge-badge iob1048 iob1049 MuiBadge-standard MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular MuiBadge-colorError css-1z0bkto" style="box-sizing: border-box; display: flex; flex-flow: wrap; -webkit-box-pack: center; justify-content: center; align-content: center; -webkit-box-align: center; align-items: center; position: absolute; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.75rem; min-width: 20px; line-height: 1; padding: 0px 6px; height: 20px; border-radius: 10px; z-index: 1; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(244, 67, 54); color: rgb(255, 255, 255); top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%;">15</span></span><span aria-label="Fehler und Warnungen anzeigen" class="MuiBadge-root css-1rzb3uu" style="box-sizing: inherit; position: relative; display: inline-flex; vertical-align: middle; flex-shrink: 0;"><span class="MuiBadge-badge iob1048 iob1050 MuiBadge-standard MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular css-1o4n2ye" style="box-sizing: border-box; display: flex; flex-flow: wrap; -webkit-box-pack: center; justify-content: center; align-content: center; -webkit-box-align: center; align-items: center; position: absolute; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; font-size: 0.75rem; min-width: 20px; line-height: 1; padding: 0px 6px; height: 20px; border-radius: 10px; z-index: 1; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%; background-color: rgb(255, 193, 7);">97</span></span><div class="iob1037" style="box-sizing: inherit; flex-grow: 1;"></div><div style="box-sizing: inherit;"></div><div class="iob1037" style="box-sizing: inherit; flex-grow: 1;"></div><p class="MuiTypography-root MuiTypography-body2 iob1038 css-68o8xu" title="Geschätzte Größe" style="box-sizing: inherit; margin: 0px 1rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; font-size: 0.875rem; line-height: 1.43; letter-spacing: 0.01071em;">Log-Größe:<span class="Apple-converted-space"> </span><span class="iob1039" style="box-sizing: inherit; font-style: italic;">737.6 KB</span></p></div><div class="MuiGrid-root MuiGrid-item iob1059 css-1wxaqej" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px; flex-direction: row; height: 854.871277px; overflow: hidden; max-width: none; caret-color: rgb(255, 255, 255); color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12.000001px;"><div class="MuiTableContainer-root iob1015 css-kge0eu" style="box-sizing: inherit; width: 2389.852783px; overflow-x: auto; height: 854.871277px;">
  | Zeit |   | Nachricht
-- | -- | -- | --
node-red.0 | 2024-05-23 00:27:45.370 | error | Exception-Code: EFATAL: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
node-red.0 | 2024-05-23 00:27:45.369 | error | RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org at new RequestError (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/opt/iobroker/iobroker-data/node-red/node_modules/request/request.js:185:22) at Request.emit (node:events:513:28) at Request.onRequestError (/opt/iobroker/iobroker-data/node-red/node_modules/request/request.js:877:8) at ClientRequest.emit (node:events:513:28) at TLSSocket.socketErrorListener (node:_http_client:494:9) at TLSSocket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)
node-red.0 | 2024-05-23 00:27:45.368 | error | unhandled promise rejection: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
node-red.0 | 2024-05-23 00:27:45.367 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
node-red.0 | 2024-05-23 00:27:45.365 | error | Node-RED: 23 May 00:27:45 - [error] [telegram sender:ac723b10.a88c78-9715c9ce.86b508] Caught exception in sender node: Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org when 
node-red.0 | 2024-05-23 00:27:44.987 | error | Exception-Code: EFATAL: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
node-red.0 | 2024-05-23 00:27:44.986 | error | RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org at new RequestError (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/opt/iobroker/iobroker-data/node-red/node_modules/request/request.js:185:22) at Request.emit (node:events:513:28) at Request.onRequestError (/opt/iobroker/iobroker-data/node-red/node_modules/request/request.js:877:8) at ClientRequest.emit (node:events:513:28) at TLSSocket.socketErrorListener (node:_http_client:494:9) at TLSSocket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)
node-red.0 | 2024-05-23 00:27:44.986 | error | unhandled promise rejection: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
node-red.0 | 2024-05-23 00:27:44.985 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</div></div>`

**Comment by windkh** [comment]
Hm I will try to reproduce it

**Comment by windkh** [comment]
please try with new version 16.0.0

**Comment by windkh** [comment]
@slev1n I could not reproduce it under windows.
On what hardware do you run node red? what node-red version ? what nodejs version?

**Comment by slev1n** [comment]
@windkh Im on raspy 4 with Debian,
node-red (v 3.1.4) is managed via iobroker
nodejs v16.13.0

Update to 16.0.1 did not resolve the error:
`node-red.0
2024-07-02 22:24:32.813	error	Exception-Code: EFATAL: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org

node-red.0
2024-07-02 22:24:32.813	error	RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org at new RequestError (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/opt/iobroker/iobroker-data/node-red/node_modules/@cypress/request/request.js:183:22) at Request.emit (node:events:513:28) at Request.onRequestError (/opt/iobroker/iobroker-data/node-red/node_modules/@cypress/request/request.js:869:8) at ClientRequest.emit (node:events:513:28) at TLSSocket.socketErrorListener (node:_http_client:494:9) at TLSSocket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)

node-red.0
2024-07-02 22:24:32.812	error	unhandled promise rejection: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org

node-red.0
2024-07-02 22:24:32.811	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

node-red.0
2024-07-02 22:24:32.809	error	Node-RED: 2 Jul 22:24:32 - [error] [telegram sender:ac723b10.a88c78-9715c9ce.86b508] Caught exception in sender node:
 Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
 when processing message: 
 {"payload":{"chatId":914678011,"type":"message","content":"-> false","options":{"chat_id":914678021,"text":"-> false"}},"_msgid":"18497aea960df2116"}

node-red.0
2024-07-02 22:24:32.377	error	Exception-Code: EFATAL: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org

node-red.0
2024-07-02 22:24:32.376	error	RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org at new RequestError (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/opt/iobroker/iobroker-data/node-red/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/opt/iobroker/iobroker-data/node-red/node_modules/@cypress/request/request.js:183:22) at Request.emit (node:events:513:28) at Request.onRequestError (/opt/iobroker/iobroker-data/node-red/node_modules/@cypress/request/request.js:869:8) at ClientRequest.emit (node:events:513:28) at TLSSocket.socketErrorListener (node:_http_client:494:9) at TLSSocket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)

node-red.0
2024-07-02 22:24:32.376	error	unhandled promise rejection: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org

node-red.0
2024-07-02 22:24:32.375	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by windkh** [comment]
Thanks for the info... I will try to analyze it.

**Comment by windkh** [comment]
@slev1n if you can reproduce it, then please add a catch node to the flow that is connected to a debug node. I want to know if that avoids node red from crashing

**Comment by slev1n** [comment]
@windkh unfortunately same problem with catch node (catch all nodes)

**Comment by windkh** [comment]
@slev1n thanks...

**Comment by windkh** [comment]
@slev1n please install next version which comes up in a few minutes and let me know if it changed anything

**Comment by windkh** [comment]
closed du to inactivity
