### ISSUE TITLE
Telegram bot blocks node red starting

### ISSUE THREAD

**Issue by WernerMa96** [windkh/node-red-contrib-telegrambot#387]
I updaten some nodes in my node-red. Deployed it...and now the telegram retrieves and error which allows not to start my node-red instance.Only way is safe start and deactivate all telegram nodes.

`21 Jul 20:13:19 - [red] Uncaught Exception:
21 Jul 20:13:19 - [error] TypeError: botCommandsForLanguage.filter is not a function
    at TelegramBotNode.setMyCommands (/home/pi/.node-red/node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js:538:70)
    at TelegramBotNode.onStarted (/home/pi/.node-red/node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js:567:18)
    at EventEmitter.emit (node:events:519:28)
    at Object.start [as startFlows] (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:409:12)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 18.640s CPU time.
`

I updaten from version 15.x to 16.0.2 but that doesnt help.

Is this an known issue?

**Comment by windkh** [comment]
I guess that you need to update your nodejs installation.
I use 18.xx
