### ISSUE TITLE
Telegram Bot not working

### ISSUE THREAD

**Issue by vongomben** [windkh/node-red-contrib-telegrambot#397]
Been trying to add a token of a bot I just created, but the bot fails to start. 

This is the error I see from the console
```

19 Dec 12:06:21 - [error] [telegram bot:9bb06da30832a919] Bot spippolo4bot stopped: Please check if the bot token is valid: MYTOKEN
Unhandled rejection Error: ETELEGRAM: 401 Unauthorized
    at C:\Users\user\.node-red\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\Users\user\.node-red\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user\.node-red\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\user\.node-red\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\user\.node-red\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\user\.node-red\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\user\.node-red\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\user\.node-red\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\user\.node-red\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\user\.node-red\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)

```

**Comment by windkh** [comment]
Do you use the same token in more than one application?

**Comment by vongomben** [comment]
nope, just created
(thanks for the quick answer)

**Comment by windkh** [comment]
Hm... just for crosschecking... create a new bot with another token and check again. If you trust me send me the token by mail and I check it for you. I assume the problem occurs immediately? Or did you have a special flow?

**Comment by vongomben** [comment]
I'm using echo example. 
which is your email?

**Comment by windkh** [comment]
It is in my profile.

**Comment by OptifySudarshanPatil** [comment]
I'm facing similar issue for creating new bot
have entered Botname as "@botname" and token from Botfather response prompt

![image](https://github.com/user-attachments/assets/c04d14b2-a92c-44fe-a6dd-bd0af7e7e694)

**Comment by windkh** [comment]
The problems you described do not fit together.
The upper screen indicates that the node failed to initialize ... 

The lower installation problem is something different. Maybe you have an old nodejs or nodered version installed?

**Comment by windkh** [comment]
@vongomben I did not receive any email from you?
