### ISSUE TITLE
Errors in node-red log

### ISSUE THREAD

**Issue by jaumemir** [windkh/node-red-contrib-telegrambot#6]
Hi
I am testing node-red-contrib-telegrambot.  I have deployed a flow to handle a BOT messages. I see these messages in the node-red log file:

2016-07-08T15:07:34.52+0200 [App/0]      ERR Unhandled rejection Error: 409 {"ok":false,"error_code":409,"description":"Conflict: terminated by other long poll or webhook"}
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at /home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/src/telegramPolling.js:72:15
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at tryCatcher (/home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at Promise._settlePromiseFromHandler (/home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at Promise._settlePromiseAt (/home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at Promise._settlePromises (/home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at Async._drainQueue (/home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at Async._drainQueues (/home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at Immediate.Async.drainQueues [as _onImmediate](/home/vcap/app/node_modules/node-red-contrib-telegrambot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
2016-07-08T15:07:34.52+0200 [App/0]      ERR     at processImmediate [as _immediateCallback](timers.js:383:17)

It is quite annoying, although maybe it is not so critical!

**Comment by windkh** [comment]
It seems that there is a second configuration node using the same token. Could that be the problem in your case?

**Comment by jaumemir** [comment]
It also happens with only one node.

**Comment by windkh** [comment]
Thanks for reporting this, I will try to reproduce it.

**Comment by jaumemir** [comment]
Well, when I mean one node, I mean "one receiving node". I have two nodes, one for sending, one for receiving.

**Comment by windkh** [comment]
You need to choose a config node for each the sender and receiver node. That config node connects to the telegram api. You can see that configuration node on the sidebar on the right. If you have to nodes there using the same bot token then you would have the same output in the logfile.

**Comment by jaumemir** [comment]
NO. I have disconnected all nodes and deleted all configuration nodes.
Then I have restarted Node-RED.
Then I have created one configuration node and connected the receiver.
ERR Messages have started to appear. So 1 conf node for 1 receiver generates ERR msgs.
--
Delete all again
Connect the SENDER node. Same effect. ERR Msgs generated in the same way.

**Comment by windkh** [comment]
Ok thanks alot!

**Comment by windkh** [comment]
Try to upgrade to latest version. Please report if the error has gone.
