### ISSUE TITLE
stripslashes php like ?

### ISSUE THREAD

**Issue by alfredolo** [windkh/node-red-contrib-telegrambot#96]
Hello, i got a problem with some special characthers.
The problem is the "_" (underscore character). Removing it fix the problem.
I have to use some sort of php like stripslashes ? What characters are affected ?
Thank you

Sending this message : 
"*Elenco degli utenti bannati :*
[@Sconosciuto](tg://user?id=106363xxxx) (*id*: 106363xxxx), *admin*:GLadiatore_85, *data*:18/01/2020 - 21:57
[@Sconosciuto](tg://user?id=100287xxxx) (*id*: 100287xxxx), *admin*:GLadiatore_85, *data*:18/01/2020 - 21:57
[@Sconosciuto](tg://user?id=100946xxxx) (*id*: 100946xxxx), *admin*:GLadiatore_85, *data*:18/01/2020 - 21:58"

I get this error : 
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 328
    at C:\Users\alfre\.node-red\node_modules\node-red-contrib-telegrambot\node_modules\node-telegram-bot-api\src\telegram.js:283:15
    at tryCatcher (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\alfre\.node-red\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by windkh** [comment]
Hm I will try to reproduce that. Thanks for reporting.
Can take some time as I am currently on a flight back to germany. Stay tuned.

**Comment by alfredolo** [comment]
Using "\\_" instead of a simple "_" fix the problem.
I have inserted this code into a javascript function just before the sender node and it fixed the problem.
Maybe some more characters are affected.

msg.payload.content = msg.payload.content.replace(/\_/g, "\\_");

**Comment by windkh** [comment]
I tried to reproduce it with this:

![image](https://user-images.githubusercontent.com/10910767/77261335-16afd780-6c8e-11ea-953d-57aa6d7c0551.png)

and it generates the following output:

![image](https://user-images.githubusercontent.com/10910767/77261342-25968a00-6c8e-11ea-8c3d-e5dcba9ce3e0.png)

It seems to work: what did I wrong?
